### ISSUE TITLE
prevent current stream from showing up

### ISSUE THREAD

**Issue by flbn** [pingdotgg/markerthing#34]
notes from stream:
- i think the biggest thing was just that it's kinda useless, editing-wise
- ugly cause the thumbnail won't render?

**Comment by mrhappyma** [comment]
It should probably look better, but it shouldn't be removed.

**Comment by nickserv** [comment]
[Source clip on Twitch](https://clips.twitch.tv/DullSlickAmazonSuperVinlin-MpordrMLMAZWmfJy)

**Comment by flbn** [comment]
meh yeah it sounded like a 'pls remove'

i'm no streamer but it makes little sense to have an ongoing stream in the editor? like, you only edit a video after it ends, really. otherwise you grab a specific clip from within the twitch app

**Comment by markflorkowski** [comment]
`https://api.twitch.tv/helix/streams?&user_id=<<SOME_USER_ID>>` endpoint should allow you to get the id of the currently live stream if there is one, which can be used to filter it out of the VODs list

API Docs: https://dev.twitch.tv/docs/api/reference/#get-streams
