### ISSUE TITLE
Export formats

### ISSUE THREAD

**Issue by t3dotgg** [pingdotgg/markerthing#35]
Exporting to "youtube chapters" would be dope (even though LosslessCut kind of already does this)

**Comment by erichardson-lee** [comment]
Don't know react for implementing the UI, but…
```ts
  const ytTimeStamps = mockedMarkers.map((marker) => {
    const startTime = Math.max(marker.position_seconds - offset, 0);

    const hours = Math.floor(startTime / 3600);
    const mins = Math.floor((startTime % 3600) / 60);
    const seconds = Math.floor(startTime % 60);

    const pad = (v: number) => v.toString().padStart(2, "0");

    return hours
      ? `${marker.description}: ${hours}:${pad(mins)}:${pad(seconds)}`
      : `${marker.description}: ${pad(mins)}:${pad(seconds)}`;
  });
```

**Comment by markflorkowski** [comment]
I think the format is

`<description> - hh:mm:ss`

**Comment by erichardson-lee** [comment]
https://support.google.com/youtube/answer/9884579

Should be fine with mm:ss style, should possibly add a check for array length >= 3 though

**Comment by markflorkowski** [comment]
I mean there is a dash instead of a colon between the description and timestamp

**Comment by t3dotgg** [comment]
https://github.com/pingdotgg/markerthing/pull/55
